artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/waasnipun/timeseries-mobile_traffic-forecast-LSTM/raw/main/dataset/Data_V3.xlsx
  local_data_file: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5