artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/waasnipun/timeseries-mobile_traffic-forecast-LSTM/raw/main/dataset/Data_V3.xlsx
  local_data_file: artifacts/data_ingestion

prepare_data:
  data_path: artifacts/data_ingestion/Data_V3.xlsx
  col_name: Ish.L.TrafficVolume.DL.GB(GB)

prepare_model:
  model_directory: artifacts/prepare_model
  error_type: mean_squared_error