artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/waasnipun/timeseries-mobile_traffic-forecast-LSTM/raw/main/dataset/Data_V3.xlsx
  local_data_file: artifacts/data_ingestion